<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>PisgahSoft.Utils.StringLibrary</PackageId>
    <Version>1.0.0</Version>
    <Authors>rockhopper</Authors>
    <Company>PisgahSoft</Company>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
