<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!-- use this to have multiple files with top level statements -->
  <ItemGroup>
    <!-- <Compile Remove="Program.cs" /> -->
    <Compile Remove="IndexAndRanges.cs" />
  </ItemGroup>

</Project>
