@GameStoreApi_HostAddress = http://localhost:5141

GET {{GameStoreApi_HostAddress}}/games

###

GET {{GameStoreApi_HostAddress}}/games/4

###

POST {{GameStoreApi_HostAddress}}/games
Content-Type: application/json

{
    "name": "Super Mario Bros. Wonder",
    "genre": "Platformer",
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###