@GameStoreApi_HostAddress = http://localhost:5141

GET {{GameStoreApi_HostAddress}}/games
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRyZXciLCJzdWIiOiJkcmV3IiwianRpIjoiY2Y0NDUzOTgiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MTQxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI3NSJdLCJuYmYiOjE3ODYzNzQ1NTksImV4cCI6MTc5NDMyMzM1OSwiaWF0IjoxNzg2Mzc0NTYwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.-zkOH6fuHEsNEqFoe8gHLWHyDzRzfFM6eCf7ZqSD6BI

###

GET {{GameStoreApi_HostAddress}}/games/mygames
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImRyZXciLCJzdWIiOiJkcmV3IiwianRpIjoiY2Y0NDUzOTgiLCJyb2xlIjoiYWRtaW4iLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MTQxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI3NSJdLCJuYmYiOjE3ODYzNzQ1NTksImV4cCI6MTc5NDMyMzM1OSwiaWF0IjoxNzg2Mzc0NTYwLCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.-zkOH6fuHEsNEqFoe8gHLWHyDzRzfFM6eCf7ZqSD6BI

###

GET {{GameStoreApi_HostAddress}}/games/mygames
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiOWFmOWE2ODMiLCJyb2xlIjoiYWRtaW4iLCJzdWJzY3JpcHRpb24iOiJzaWx2ZXIiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDo1MTQxIiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NzI3NSJdLCJuYmYiOjE3ODYzODAxNzcsImV4cCI6MTc5NDMyODk3NywiaWF0IjoxNzg2MzgwMTc4LCJpc3MiOiJkb3RuZXQtdXNlci1qd3RzIn0.PiW7MphblQWRMgDYz3w0uEhJ3bS5Cvd0jhK7v5cx5Sk
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InBsYXllcjEiLCJzdWIiOiJwbGF5ZXIxIiwianRpIjoiMjUyNDY2ZDEiLCJyb2xlIjoiYWRtaW4iLCJzdWJzY3JpcHRpb24iOiJnb2xkIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTE0MSIsImh0dHBzOi8vbG9jYWxob3N0OjcyNzUiXSwibmJmIjoxNzg2MzgwMzM2LCJleHAiOjE3OTQzMjkxMzYsImlhdCI6MTc4NjM4MDMzNywiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.qQrzAQEvOEkJltxDGMeroHYRbie6EFDc17aUJ2JURTo
###

GET {{GameStoreApi_HostAddress}}/genres

###

GET {{GameStoreApi_HostAddress}}/games/2

###

POST {{GameStoreApi_HostAddress}}/games
Content-Type: application/json

{
    "name": "Super Mario Bros. Wonder",
    # "genre": "Platformer",
    "genreId": 3,
    "price": 59.99,
    "releaseDate": "2023-10-20"
}

###

POST  {{GameStoreApi_HostAddress}}/games
Content-Type: application/json

{
    "name": "Street Fighter II",
    "genreId": 1, 
    "price": 9.99,
    "releaseDate": "1991-02-01"
}

###

PUT {{GameStoreApi_HostAddress}}/games/3
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": 1, 
    "price": 19.99,
    "releaseDate": "1992-07-15"
}

###

DELETE  {{GameStoreApi_HostAddress}}/games/2

###
